const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const ObjectId = mongoose.Schema.Types.ObjectId;

const UUID_LENGTH = 36;


const schema = new Schema({
   sheet: {
      type: String,
      required: true,
      ref: 'Sheet'
   },
   row: {
      type: ObjectId,
      required: true,
      ref: 'Row'
   },
   headerKey: {
      type: String,
      required: true,
      // validate: {
      //    validator: (v) => (typeof v == 'string') && (v.length == UUID_LENGTH) // id length generated by uuid
      // }
   },
   histories: Array
}, {
   timestamps: true
});

module.exports = schema;
